version: '3.3'
services:
  web:
    container_name: web-phalcon5-skip-attributes
    image: web-phalcon5-skip-attributes
    restart: always
    volumes:
      - './phalcon5_app:/src'
    ports:
      - '8057:80'
    build:
      dockerfile: Dockerfile
      context: ./web
  db:
    container_name: db-phalcon5-skip-attributes
    image: db-phalcon5-skip-attributes
    restart: always
    volumes:
      - '${LOG}:/tmp/dump'
      - '${INITDB}:/docker-entrypoint-initdb.d'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '${POSTGRES_PASS}'
    command: ["postgres", "-c", "logging_collector=on", "-c", "log_directory=/tmp/dump", "-c", "log_filename=postgresql.log", "-c", "log_statement=all"]
    ports:
      - '5462:5432'
    build:
      dockerfile: Dockerfile
      context: ./db